apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lhl-dev
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 2
            tcpSocket:
              port: 80
            periodSeconds: 10
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
            limits:
              cpu: 0.3
              memory: 1024Mi
      volumes:
        - name: nginx-config
          hostPath:
            path: /Users/hl.l/workspace/learn-k8s-yaml/data/nginx # 要挂载的路径，/d 表示windows下的D盘
            type: DirectoryOrCreate
