apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort  #这里代表是NodePort类型的
  ports:
    - port: 80  #供集群内部使用的端口
      targetPort: 80 #容器暴露出来的端口
      protocol: TCP
      nodePort: 30080 #所有的节点都会开放此端口，此端口供外部调用, The range of valid ports is 30000-32767
  selector:
    app: nginx
